config/routes.rb
Rails.application.routes.draw do

	root 'home#home_index'

	# registration routes
	get 'signup' => 'users#new', :as => :signupPage
	post 'signup-user' => 'users#create', :as => :signupUser
	# ^ same as below 
	# get 'register/signup' => 'home#signupPage', :as => :signupPage
	# post 'register/signup-user' => 'home#signupUser', :as => :signupUser
	
	# authentication routes
	get 'login' => 'sessions#new', :as => :loginPage
	post 'login' => 'sessions#create', :as => :loginUser
	delete 'logout' => 'sessions#destroy', :as => "logoutUser"

	# home route
	get 'home/index' => 'home#home_index', :as => :homeIndex

	# dashboard
	get 'dashboard' => 'home#dashboard', :as => :dashboard

	# groups routes
	get 'group/:group_id' => 'group#get_group', :as => :group
	post 'create-group' => 'home#create_group', :as => "createGroup"
	# post 'create-group' => 'group#create_group', :as => :createGroup

	# bills routes
	get 'group/:group_id/bill/:bill_id' => 'bill#get_bill', :as => :bill
	post 'group/create-bill' => 'home#create_group_bill', :as => :createGroupBill

	# activity routes
	get 'activities' => 'activities#get_activities', :as => :activities


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :require_user, only: [:dashboard, :activities, :group]
	protect_from_forgery

	layout "application", only: [:homeIndex, :dashboard]

	def home_index
		@title = "Splitwise"
		@register = nil
	end

	def dashboard
		@title = "Dashboard | Splitwise"
		@user = User.find(session[:user_id])
		@user_groups = @user.groups
		user_debts = Debt.where(:member2 => @user.id).where(['member1 <> ?', @user.id]).group(:member1).sum(:owes_amount)
		user_friends = UnregistUser.where(:id => user_debts.keys)
		@friends = {}
		user_friends.each do |u|
			@friends[u.name] = (user_debts[u.id]).round(2)
		end
		@total_user_spent = Debt.where(:member1 => @user.id).sum(:owes_amount).round(2)
		@total_user_owed = Debt.where(['member1 <> ? AND member2 = ?', @user.id, @user.id]).sum(:owes_amount).round(2)
		@total_user_owes = 0
	end

	def create_group
		@title = "Dashboard | Splitwise"

		members = params[:member]
		member_emails = params[:member_email]

		if members.size != member_emails.size
			flash[:error_group] = "Member and Emails mismatch"
			render('dashboard')
		end

		group = Group.new
		group.name = params[:group_name]
		group.description = params[:group_description]
		group.user = current_user

		if group.save
			activity = Activity.new
			activity.activity_details = "You added group " + group.name
			activity.user = @user
			activity.save
			for i in 0..members.size-1
				if members[i] != ''
					unregist_user = UnregistUser.new
					unregist_user.name = members[i]
					unregist_user.email = member_emails[i]
					group.unregist_users << unregist_user
					a = Activity.new
					a.activity_details = "		Member " + unregist_user.name + " added to group " + group.name
					a.user = @user
					a.save
				end
			end
			flash[:notice] = "Group created Successfull"
			redirect_to :controller => 'home', :action => 'dashboard'
		else
			flash[:notice] = "Group couldn\'t be created"
			redirect_to :controller => 'home', :action => 'dashboard'
		end
	end

	def create_group_bill
		@title = "Dashboard | Splitwise"
		@user = User.find(session[:user_id])

		group = Group.find(params[:group_id])
		bill = Bill.new
		bill.name = params[:bill_name]
		bill.descrption = params[:bill_description]
		bill.total_amount = params[:total_amount]
		bill.split_method = params[:split_method]
		bill.group = group

		if group.bills << bill
			activity = Activity.new
			activity.activity_details = "	Bill " + bill.name + " added to group " + group.name
			activity.user = @user
			activity.save

			total_amount = bill.total_amount
			split_method = bill.split_method
			no_of_users = group.unregist_users.size + 1 # the admin of group
			unregist_users_by_shares = params[:unregist_user_id_share]
			unregist_users_by_per = params[:unregist_user_id_per]
			regist_user_by_share = params[:regist_user_id_share]
			regist_user_by_per = params[:regist_user_by_per]

			if split_method == "Split Equally"
				individual_amt = total_amount / no_of_users.to_f
				individual_amt = individual_amt.round(2)
				
				group.unregist_users.each do |unregist_u|
					debt = Debt.new
					debt.member1 = unregist_u.id
					debt.member2 = @user.id
					debt.owes_amount = individual_amt
					debt.unregist_mem1 = true
					debt.unregist_mem2 = false
					debt.group = group
					debt.bill = bill

					if !debt.save
						flash[:notice] = "Bill creation fail"
						render 'group', :group_id => group.id
						return
					end
				end
				# user debt
				debt = Debt.new
				debt.member1 = @user.id
				debt.member2 = @user.id
				debt.owes_amount = individual_amt
				debt.unregist_mem1 = false
				debt.unregist_mem2 = false
				debt.group = group
				debt.bill = bill

				# might not store then, the whole thing is wrong
				# fix it later
				if !debt.save
					flash[:notice] = "Bill creation fail"
					render 'group', :group_id => group.id
					return
				end

				flash[:notice] = "Bill creation Successfull"
				redirect_to :contoller => 'home', :action => :group, :group_id => group.id, :notice => "Bill creation Successfull"
				return

			elsif split_method == "Split By Shares"
				inputShares = params["split-share"]
				shares = []
				totalShares = 0
				for i in 0..no_of_users-1
					shares[i] = inputShares[i].to_i
					totalShares += shares[i]
				end

				actualIndividualAmt = total_amount / totalShares.to_f;
				actualIndividualAmt = actualIndividualAmt.round(2);

				finalIndividualShares = []
				for i in 0..no_of_users-1
					finalIndividualShares[i] = shares[i] * actualIndividualAmt
				end

				for i in 0..no_of_users-2
					debt = Debt.new
					debt.member1 = unregist_users_by_shares[i].to_i
					debt.member2 = @user.id
					debt.owes_amount = finalIndividualShares[i]
					debt.unregist_mem1 = true
					debt.unregist_mem2 = false
					debt.group = group
					debt.bill = bill

					if !debt.save
						flash[:notice] = "Bill creation fail"
						render 'group', :group_id => group.id
						return
					end
				end
				# user debt
				debt = Debt.new
				debt.member1 = @user.id
				debt.member2 = @user.id
				debt.owes_amount = finalIndividualShares[finalIndividualShares.size-1]
				debt.unregist_mem1 = false
				debt.unregist_mem2 = false
				debt.group = group
				debt.bill = bill

				# might not store then, the whole thing is wrong
				# fix it later
				if !debt.save
					flash[:notice] = "Bill creation fail"
					render 'group', :group_id => group.id
					return
				end

				flash[:notice] = "Bill creation Successfull"
				redirect_to :contoller => 'home', :action => :group, :group_id => group.id, :notice => "Bill creation Successfull"
				return

			elsif split_method == "Split By %"
				inputPers = params["split-per"]
				pers = []
				totalPers = 0
				for i in 0..no_of_users-1
					shares[i] = inputPers[i].to_i
					totalPers += shares[i]
				end

				left = 100 - totalPers

				if left < 0 || left > 0
					flash[:error_group] = "Something wrong with the split"
					render('group')
					return
				end

				finalIndividualShares = []

				for i in 0..no_of_users-1
					finalIndividualShares[i] = (( (pers[i] * total_amount) / 100.0 ).round(2))
				end

				for i in 0..no_of_users-2
					debt = Debt.new
					debt.member1 = unregist_users_by_per[i].to_i
					debt.member2 = @user.id
					debt.owes_amount = finalIndividualShares[i]
					debt.unregist_mem1 = true
					debt.unregist_mem2 = false
					debt.group = group
					debt.bill = bill

					if !debt.save
						flash[:notice] = "Bill creation fail"
						render 'group', :group_id => group.id
						return
					end
				end
				# user debt
				debt = Debt.new
				debt.member1 = @user.id
				debt.member2 = @user.id
				debt.owes_amount = finalIndividualShares[finalIndividualShares.size-1]
				debt.unregist_mem1 = false
				debt.unregist_mem2 = false
				debt.group = group
				debt.bill = bill

				# might not store then, the whole thing is wrong
				# fix it later
				if !debt.save
					flash[:notice] = "Bill creation fail"
					render 'group', :group_id => group.id
					return
				end

				flash[:notice] = "Bill creation Successfull"
				redirect_to :contoller => 'home', :action => :group, :group_id => group.id, :notice => "Bill creation Successfull"
				return
			end
		else
			flash[:error_group] = "Something wrong with the bill"
			render('group')
			return
		end
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activities.html.erb
<% if flash[:error_group] %>
<div class="container">
	<div class="alert alert-success">
		<b><%= flash[:error_group] %></b>
	</div>
</div>
<br />
<% end %>

<div class="container">
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
		  <a href="<%= dashboard_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Dashboard</a>
		  <a href="<%= activities_path %>" class="list-group-item highlight-group"><span class="glyphicon glyphicon-chevron-right"></span> Recent activity</a>
		  <hr size="1">
		  <a  href="#" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> All expenses</a>
		  <li class="list-group-item highlight"><span class="glyphicon glyphicon-tags">&nbsp; &nbsp;</span> Groups</li>
		  <% @user_groups.each do |group| %>
		  	<a href="<%= group_path(group.id) %>" class="list-group-item groupnames">&nbsp; &nbsp; &nbsp;<span class="glyphicon glyphicon-tag"></span><%= group.name %></a>
		  <% end %>
		</ul>
	</div>
	<div class="col-lg-7 dashboard-main">
		<div class="row dashboard-main-row1">
			<h1><%= @title %></h1>
		</div>
		<hr size="2">
		<div class="row dashboard-main-row2">
			<table class="table-bordered table-striped table">
				<tbody>
				<% @user_activities.each do |activity| %>
					<tr>
						<td>
							<%= activity.activity_details %><br />
							<span style="color: #e91e63;">&nbsp;&nbsp;&nbsp;&nbsp;
								<%= activity.created_at.to_s.split(" ")[0] %>
							</span>
							<span style="color: #03a9f4;">&nbsp;&nbsp;
								<%= activity.created_at.to_s.split(" ")[1] %>
							</span>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
		<hr size="2">
	</div>
</div>

app/views/home/bill.html.erb
<% if flash[:error] %>
<div class="container">
	<div class="alert alert-success">
		<b><%= flash[:error] %></b>
	</div>
</div>
<br />
<% end %>

<div class="container">
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
		  <a href="<%= dashboard_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Dashboard</a>
		  <a href="<%= activities_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Recent activity</a>
		  <hr size="1">
		  <a class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> All expenses</a>
		  <li class="list-group-item highlight"><span class="glyphicon glyphicon-tags">&nbsp;</span> GROUPS</li>
		  <% @user_groups.each do |group| %>
		  	<a href="<%= group_path(group.id) %>" class="list-group-item groupnames <% if @group.id == group.id %> highlight-group  <% end %>">&nbsp; &nbsp; &nbsp;<span class="glyphicon glyphicon-tag"></span><%= group.name %></a>
		  <% end %>
		</ul>
	</div>
	<div class="col-lg-7 dashboard-main">
		<div class="row dashboard-main-row1">
			<h1><%= @title %> - <%= @group.name %></h1>
			<button class="btn btn-default"> Settle Up</button>
		</div>
		<hr size="2">
		<div class="row">
			<span class="bill-descrption-text">Bill Description</span>
			<p class="billpage-descrption"><%= @bill.descrption %></p>
			<hr size="2">
			<span class="bill-descrption-text">Bill Amount</span>
			<span class="bill-total_amount">$<%= @bill.total_amount %></span>
			<span class="bill-descrption-text">Split Method</span>
			<span class="bill-split-method"><%= @bill.split_method %></span>
		</div>
		<hr size="2">
		<div class="row dashboard-main-row2">
			<div class="col-lg-4">
				<center>
				<b>total bill amount</b><br /><br />	
				<span class="total-spent">$ <%= @bill.total_amount %></span>
				</center>
			</div>
			<div class="col-lg-4">
				<center>
				<b>total bill debts</b><br /><br />
				<span class="total-owes">$ <%= @total_bill_debt %></span>
				</center>
			</div>
			<div class="col-lg-4">
				<center>
				<b>number of members</b><br /><br />
				<span class="total-owed"><%= @bill_members_debts.size %></span>
				</center>
			</div>
		</div>
		<hr size="2">
		<div class="row" style="padding: 8px">
			<p style="padding: 8px; font-size:25px;">Bill Debts</p>
			<div class="list-group">
				<% @bill_members_debts.each do |name, debt| %>
					<a class="list-group-item">
						<div class="bill-member">
							<%= name %>
						</div>
						<p class="bill-member-debt">
							$<%= debt %>
						</p>
					</a>
				<% end %>
				<a class="list-group-item">
					<div class="bill-member">
						<b><%= @user.username %> (you) </b>
					</div>
					<p class="bill-member-user-paid">
						$<%= @user_paid %>
					</p>
				</a>
			</div>
		</div>
	</div>
	<div class="col-lg-2 list-group">
		
	</div>
</div>

app/views/home/dashboard.html.erb
<div class="container">
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
		  <a href="<%= dashboard_path %>" class="list-group-item highlight-group"><span class="glyphicon glyphicon-chevron-right"></span> Dashboard</a>
		  <a href="<%= activities_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Recent activity</a>
		  <hr size="1">
		  <a  href="#" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> All expenses</a>
		  <li class="list-group-item highlight"><span class="glyphicon glyphicon-tags">&nbsp; &nbsp;</span> Groups</li>
		  <% @user_groups.each do |group| %>
		  	<a href="<%= group_path(group.id) %>" class="list-group-item groupnames">&nbsp; &nbsp; &nbsp;<span class="glyphicon glyphicon-tag"></span><%= group.name %></a>
		  <% end %>
		</ul>
	</div>
	<div class="col-lg-7 dashboard-main">
		<div class="row dashboard-main-row1">
			<h1><%= @title %></h1>
			<!-- <button class="btn btn-primary">Add Bill</button>
			<button class="btn btn-default"> Settle Up</button> -->
			<button class="btn btn-success" type="button" data-toggle="modal" data-target="#newGroupModal">New group</button>
		</div>
		<hr size="2">
		<div class="row dashboard-main-row2">
			<div class="col-lg-4">
				<center>
				<b>total spent</b><br /><br />
				<span class="total-spent">$ <%= @total_user_spent %></span>
				</center>
			</div>
			<div class="col-lg-4">
				<center>
				<b>you owe</b><br /><br />
				<span class="total-owes">$ <%= @total_user_owes %></span>
				</center>
			</div>
			<div class="col-lg-4">
				<center>
				<b>you are owed</b><br /><br />
				<span class="total-owed">$ <%= @total_user_owed %></span>
				</center>
			</div>
		</div>
		<hr size="2">
	</div>
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
			<li class="list-group-item highlight">FRIENDS</li>
			<hr size="1">
			<% @friends.each do |name, owe_amt| %>
				  <a class="list-group-item"><span class="glyphicon glyphicon-user"></span>
					<span class="friend-name"><%= name %></span><br />
					<span class="friend-amount">$ <%= owe_amt %></span>
				  </a>
			<% end %>
		</ul>
	</div>
</div>


<!-- New Group Modal -->
<div id="newGroupModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create a New Group</h4>
      </div>
      <div class="modal-body">
      	<form method="post" action="<%= createGroup_path %>">
      		<div class="form-group">
      			<input type="text" name="group_name" class="form-control" placeholder="Group Name" required />
      		</div>
      		<div class="form-group">
      			<textarea rows="3" class="form-control" name="group_description" placeholder="Group Description ...." required></textarea>
      		</div>
      		<hr size="2">
      		<p>GROUP MEMBERS</p>
			<p>
				<span class="glyphicon glyphicon-user"></span>
				<b><%= @user.username %></b>&nbsp;(<i><%= @user.email %></i>)
			</p>
			<div id="member-section">
				<p id="add-members">
					<div class="form-group form-inline">
						<input type="text" name="member[]" placeholder="Member 1" class="form-control" required />
						<input type="email" name="member_email[]" placeholder="Email" class="form-control" required/>
					</div>
				</p>
				<p id="add-members">
					<div class="form-group form-inline">
						<input type="text" name="member[]" placeholder="Member 2" class="form-control" />
						<input type="email" name="member_email[]" placeholder="Email" class="form-control" />
					</div>
				</p>
				<p id="add-members">
					<div class="form-group form-inline">
						<input type="text" name="member[]" placeholder="Member 1" class="form-control" />
						<input type="email" name="member_email[]" placeholder="Email" class="form-control" />
					</div>
				</p>
			</div>
			<p>
				<button type="button" class="btn btn-default" id="addMemberBtn" onclick="addMemberRow()">+ Add member</button>
			</p>
			<hr size="2">
			<button type="submit" class="btn btn-primary">Create</button>
      	</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/home/group.html.erb
<% if flash[:error] %>
<div class="container">
	<div class="alert alert-success">
		<b><%= flash[:error] %></b>
	</div>
</div>
<br />
<% end %>

<div class="container">
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
		  <a href="<%= dashboard_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Dashboard</a>
		  <a href="<%= activities_path %>" class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> Recent activity</a>
		  <hr size="1">
		  <a class="list-group-item"><span class="glyphicon glyphicon-chevron-right"></span> All expenses</a>
		  <li class="list-group-item highlight"><span class="glyphicon glyphicon-tags">&nbsp;</span> GROUPS</li>
		  <% @user_groups.each do |group| %>
		  	<a href="<%= group_path(group.id) %>" class="list-group-item groupnames <% if @group.id == group.id %> highlight-group  <% end %>">&nbsp; &nbsp; &nbsp;<span class="glyphicon glyphicon-tag"></span><%= group.name %></a>
		  <% end %>
		</ul>
	</div>
	<div class="col-lg-7 dashboard-main">
		<div class="row dashboard-main-row1">
			<h1><%= @title %></h1>
			<p class="billpage-descrption"><%= @group.description %></p>
			<hr size="2">
			<button class="btn btn-primary" type="button" data-toggle="modal" data-target="#newGroupBillModal">Add Bill</button>
			<button class="btn btn-default"> Settle Up</button>
		</div>
		<hr size="2">
		<div class="row dashboard-main-row2">
			<div class="row">
				<div class="col-lg-4">
					<center>
					<b>total spent in group</b><br /><br />
					<span class="total-spent">$<%= @total_spent_in_this_group  %></span>
					</center>
				</div>
				<div class="col-lg-4">
					<center>
					<b>you spent in this group</b><br /><br />
					<span class="total-owes">$<%= @total_user_spent_in_this_group %></span>
					</center>
				</div>
				<div class="col-lg-4">
					<center>
					<b>group owes you</b><br /><br />
					<span class="total-owed">$
					<%= @total_use_owes_from_this_group %></span>
					</center>
				</div>
			</div>
		</div>
		<hr size="2">
		<div class="row" style="padding: 8px;">
			<p style="padding: 8px; font-size:25px;">Group Bills</p>
			<div class="list-group">
				<% @group_bills.each do |bill| %>
					<a href="<%= bill_path(@group.id, bill.id) %>"
					class="list-group-item">
						<div class="bill-title">
							<%= bill.name %>
						</div>
						<p class="bill-descrption">
							<%= bill.descrption %>
						</p>
						<div class="bill-amount">
							$ <%= bill.total_amount %>
						</div>
					</a>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-lg-2 list-group">
		<ul class="nav nav-pills nav-stacked">
			<li class="list-group-item highlight">GROUP MEMBERS</li>
			<hr size="1">
			<% @group_members_debts.each do |name, amt| %>
				<a href="#" class="list-group-item"><span class="glyphicon glyphicon-user"></span>
					<span class="friend-name"><%= name %></span><br />
					<span class="friend-amount">$ <%= amt %></span>
				</a>
			<% end %>
			<a href="#" class="list-group-item">
				<p>
					<span class="glyphicon glyphicon-user"></span>
					<%= @user.username %><b>(you)</b>
				</p>
			</a>
		</ul>
	</div>
</div>

<!-- New Group Modal -->
<div id="newGroupBillModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Bill with
        	<b>you</b> and all of <span class="well-custom"><%= @group.name %></span></h4>
      </div>
      <div class="modal-body">
      	<form method="post" action="<%= createGroupBill_path %>">
      		<div class="form-group">
      			<input type="text" name="bill_name" class="form-control" placeholder="Bill Name" required />
      		</div>
      		<div class="form-group">
      			<textarea rows="3" class="form-control" name="bill_description" placeholder="Bill Description ...." required></textarea>
      		</div>
      		<div class="form-group form-inline">
      			<label class="dollar">Total Amount</label><br />
      			<label class="dollar">$</label>
      			<input type="number" name="total_amount" placeholder="0.00" id="total_amount" class="form-control" required />
      		</div>
      		<div class="form-group">
	      		<label class="dollar">Split Method</label><br />
      			<select class="form-control" name="split_method" id="split_method" onclick="splitCalculation(<%= @group.unregist_users.size %> + 1)">
      				<option value="Split Equally">Split Equally</option>
      				<option value="Split By Shares">Split By Shares</option>
      				<option value="Split By %">Split By %</option>
      			</select>
      		</div>
      		<center>
	      		<div class="row" id="split-section-1">
			      	($&nbsp;<span id="split-calculation">0.0</span>/person)
	      		</div>
	      	</center>
      		<div class="row form-inline" id="split-section-2" style="display: none;">
	      		<div class="list-group">
	      			<% variable = 1 %>
	      			<% @group.unregist_users.each do |u| %>
	      				<a class="list-group-item">
		      				<div class="row">
		      					<div class="col-lg-4 col-lg-offset-1">
			      					<span><%= u.name %></span>
			      					($&nbsp;<span id="individual-amt-<%= variable %>"></span>)
		      					</div>
		      					<div class="col-lg-3" >
		      						<input type="number" min="0" name="split-share[]" value="1" class="form-control"
		      						onchange="splitByShareCalc(<%= @group.unregist_users.size %> + 1)" 
		      						id="split-share-<%= variable %>" />
		      						<label>share(s)</label>
		      					</div>
		      				</div>
		      				<input type="hidden" name="unregist_user_id_share[]" value="<%= u.id %>">
	      				</a>
	      				<% variable = variable + 1 %>
	      			<% end %>
	      			<a class="list-group-item">
		      			<div class="row">
		      				<div class="col-lg-4 col-lg-offset-1">
			      					<span>
			      					<%= @user.username %></span>
			      					($&nbsp;<span id="individual-amt-<%= variable %>">0.0
			      					</span>)
		      				</div>
		      				<div class="col-lg-3">
		      					<input type="number" min="0" name="split-share[]" value="1" class="form-control" id="split-share-<%= variable %>"
		      					onchange="splitByShareCalc(<%= @group.unregist_users.size %> + 1)" 
		      					id="split-share-<%= variable %>" />
		      					<label>share(s)</label>
		      				</div>
		      			</div>
		      			<input type="hidden" name="regist_user_id_share" value="<%= @user.id %>">
	      			</a>
      			</div>
      		</div>
      		<div class="row" id="split-section-3" style="display: none;">
      			<div class="list-group">
	      			<% variable = 1 %>
	      			<% @group.unregist_users.each do |u| %>
	      				<a class="list-group-item">
		      				<div class="row">
		      					<div class="col-lg-4 col-lg-offset-1">
			      					<span><%= u.name %></span>
			      					($&nbsp;<span id="individual-amt-per-<%= variable %>">0</span>)
		      					</div>
		      					<div class="col-lg-3" >
		      						<input type="number" min="0" name="split-per[]" value="0" 
		      						class="form-control"
		      						onchange="splitByPerCalc(<%= @group.unregist_users.size %> + 1)"
		      						id="split-per-<%= variable %>" />
		      						<label>%</label>
		      					</div>
		      				</div>
		      				<input type="hidden" name="unregist_user_id_per[]" value="<%= u.id %>">
	      				</a>
	      				<% variable = variable + 1 %>
	      			<% end %>
	      			<a class="list-group-item">
		      			<div class="row">
		      				<div class="col-lg-4 col-lg-offset-1">
			      					<span>
			      					<%= @user.username %></span>
			      					($&nbsp;<span id="individual-amt-per-<%= variable %>">0
			      					</span>)
		      				</div>
		      				<div class="col-lg-3">
		      					<input type="number" min="0" name="split-per[]" value="0" class="form-control" id="split-per-<%= variable %>"
		      					onchange="splitByPerCalc(<%= @group.unregist_users.size %> + 1)" />
		      					<label>%</label>
		      				</div>
		      			</div>
		      			<input type="hidden" name="regist_user_id_per" value="<%= @user.id %>">
	      			</a>
	      			<a class="list-group-item">
	      				<div class="row">
	      					<div class="col-lg-4 col-lg-offset-4">
		      					<p>
		      						<b>TOTAL</b> - <span id="total-per"><b>0</b></span>%
		      					</p>
		      					<br />
		      					<p>
		      						Left - <span id="left-per">100</span>%
		      					</p>
	      					</div>
	      				</div>
	      			</a>
      			</div>
      		</div>
      		<input type="hidden" name="group_id" value="<%= @group.id %>" />
			<button type="submit" class="btn btn-primary">Create</button>
      	</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/home/homeIndex.html.erb
<div class="container">
	<center>
		<div class="row">
			<h1 class="title">Split expenses with friends.</h1>
			<h3>
				<b>Share</b> bills. <b>Make sure</b> everyone gets paid back.
				<b>Totally free</b> for web and Android(<b>coming soon</b>).
			</h3>
		</div>
		<div class="row">
			<img src="/images/dashboard1.png" class="img-responsive home-img" alt="dashboard" />		
		</div>
		<center>
			<div class="row">
				<a href="<%= signupPage_path %>" class="btn btn-primary btn-block home-button">Get Started</a>
			</div>
		</center>
	</center>
</div>